"""your message

Revision ID: 39699ab21413
Revises: 1e7d0d430167
Create Date: 2024-07-05 12:09:34.123736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39699ab21413'
down_revision = '1e7d0d430167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###